// Catálogo único dos módulos/telas do Console v2.
// Fonte de verdade compartilhada entre o menu (ConsoleV2) e o editor de
// módulos por tenant (Clientes → "Telas"). module id = tenant_modules.module_key.
export const GRUPOS = [
  { label: 'Início', items: [
    { id: 'visao', ic: 'i-grid', label: 'Visão Geral' },
    { id: 'deli', ic: 'i-bot', label: 'DELI' },
  ]},
  { label: 'Operação', items: [
    { id: 'crm', ic: 'i-users', label: 'Clientes' },
    { id: 'lojas', ic: 'i-store', label: 'Lojas' },
    { id: 'chat',             ic: 'i-chat',  label: 'Chat ao Vivo' },
    // ponytail: temporário — remover quando o Wandson terminar de comparar legado x cv2
    { id: 'chat-legado',      ic: 'i-clock', label: 'Chat ao Vivo (legado)' },
    { id: 'respostas-rapidas', ic: 'i-reply', label: 'Respostas Rápidas' },
    { id: 'mia', ic: 'i-eye', label: 'Conversas · MIA' },
    { id: 'aprovacoes', ic: 'i-check', label: 'Aprovações' },
    { id: 'recontratacao', ic: 'i-reply', label: 'Re-contratação' },
    { id: 'sofia', ic: 'i-bot', label: 'SOFIA' },
    { id: 'disparos', ic: 'i-reply', label: 'Disparos' },
    { id: 'cora', ic: 'i-cash', label: 'Cobrança' },
    { id: 'defesa', ic: 'i-shield', label: 'Defesa Comercial' },
    { id: 'radar', ic: 'i-radio', label: 'iFood: Dashboard' },
    { id: 'cardapio-ifood', ic: 'i-menu', label: 'iFood: Cardápio' },
    { id: 'espacos', ic: 'i-layers', label: 'Espaços' },
    { id: 'ativar', ic: 'i-plug', label: 'Ativar loja' },
    { id: 'campanhas', ic: 'i-flag', label: 'Campanhas' },
    { id: 'grupos', ic: 'i-users', label: 'WhatsApp: Grupos' },
    { id: 'contratos', ic: 'i-doc', label: 'Contratos' },
  ]},
  // Renomeado/agrupado 2026-07-01 (QA go-live Karina, bug #7): antes espalhado
  // dentro de "Operação" com nomenclatura inconsistente (travessão, abreviação
  // com ponto). Agrupado por assunto — mesmos ids/module_key, só label/grupo mudou.
  { label: 'Avaliações', items: [
    { id: 'avaliacoes', ic: 'i-eye', label: 'Avaliações Recebidas' },
    { id: 'resp-avaliacoes', ic: 'i-star', label: 'Respostas de Avaliações' },
    { id: 'csat', ic: 'i-check', label: 'Satisfação do Atendimento (CSAT)' },
    { id: 'nps', ic: 'i-target', label: 'Lealdade da Marca (NPS)' },
    { id: 'controle-atendimentos', ic: 'i-chart', label: 'Controle de Atendimento' },
    { id: 'avaliacao-config', ic: 'i-gear', label: 'Configurações de Avaliação' },
  ]},
  { label: 'Agentes IA', items: [
    { id: 'hub', ic: 'i-bot', label: 'Painel Agentes' },
    { id: 'catalogo', ic: 'i-box', label: 'Catálogo' },
    { id: 'estudio', ic: 'i-palette', label: 'Estúdio de Conteúdo' },
    { id: 'lara-editorial', ic: 'i-palette', label: 'LARA Editorial' },
    { id: 'lara', ic: 'i-bot', label: 'LARA' },
    { id: 'tarefas-globais', ic: 'i-list', label: 'Tarefas Globais' },
    { id: 'automacoes', ic: 'i-zap', label: 'Automações' },
    { id: 'habilidades', ic: 'i-zap', label: 'Habilidades' },
    { id: 'analise', ic: 'i-chart', label: 'Análise de Loja' },
    { id: 'cardapio', ic: 'i-menu', label: 'Cardápio' },
    { id: 'multicanal', ic: 'i-layers', label: 'Multicanal' },
    { id: 'construtor', ic: 'i-bot', label: 'Construtor de Agentes' },
    { id: 'oracle', ic: 'i-bot', label: 'Oracle (criar agente)' },
    { id: 'inbox', ic: 'i-reply', label: 'Inbox dos Agentes' },
    { id: 'tarefas', ic: 'i-list', label: 'Tarefas agendadas' },
    { id: 'gatilhos', ic: 'i-zap', label: 'Gatilhos' },
    { id: 'heartbeats', ic: 'i-radio', label: 'Heartbeats' },
    { id: 'atividade', ic: 'i-list', label: 'Atividade' },
    { id: 'metas', ic: 'i-target', label: 'Metas' },
    { id: 'topicos', ic: 'i-flag', label: 'Tópicos' },
    { id: 'modelos', ic: 'i-doc', label: 'Modelos' },
    { id: 'config', ic: 'i-gear', label: 'Config de Agentes' },
  ]},
  { label: 'Dados', items: [
    { id: 'arquivos', ic: 'i-folder', label: 'Arquivos' },
    { id: 'links', ic: 'i-link', label: 'Links compartilhados' },
    { id: 'memoria', ic: 'i-brain', label: 'Memória dos agentes' },
    { id: 'conhecimento', ic: 'i-book', label: 'Conhecimento (RAG)' },
    { id: 'custos', ic: 'i-dollar', label: 'Custos de IA' },
    { id: 'importar', ic: 'i-save', label: 'Importar relatórios' },
    { id: 'relatorios', ic: 'i-chart', label: 'Relatórios' },
  ]},
  { label: 'Sistema', items: [
    { id: 'usuarios', ic: 'i-users', label: 'Usuários e equipe', adminOnly: true },
    { id: 'configsys', ic: 'i-gear', label: 'Configurações' },
    { id: 'clientesplat', ic: 'i-users', label: 'Clientes (plataforma)' },
    { id: 'marca', ic: 'i-droplet', label: 'Marca' },
    { id: 'provedores', ic: 'i-cpu', label: 'Provedores de IA' },
    { id: 'integracoes', ic: 'i-plug', label: 'Integrações' },
    { id: 'vendaerp', ic: 'i-box', label: 'VendaERP' },
    { id: 'sistemas', ic: 'i-box', label: 'Sistemas externos' },
    { id: 'onboarding', ic: 'i-grid', label: 'Onboarding' },
    { id: 'acesso', ic: 'i-key', label: 'Acesso por usuário' },
    { id: 'auditoria', ic: 'i-scroll', label: 'Auditoria' },
    { id: 'notificacoes', ic: 'i-bell', label: 'Notificações' },
    { id: 'monitor', ic: 'i-radio', label: 'Monitor de Agentes' },
    { id: 'pipeline', ic: 'i-zap', label: 'Pipeline ao Vivo' },
  ]},
];
